# Docker file for Image Deployment using python image
FROM python:3.7.1
LABEL Author="Arun K Singh"
LABEL version="0.1"
ENV PYTHONDONTWRITEBYTECODE 1
ENV FLASK_APP "main.py"
ENV FLASK_ENV "development"
ENV FLASK_DEBUG True
RUN mkdir /app
WORKDIR /app
COPY . /app/
# RUN clause performs upgrade of pip and install the Flask App dependencies
RUN pip install --upgrade pip && \
    pip install pipenv && \
    pip install Flask && pip install Jinja2 && pip install requests
ADD . /app
EXPOSE 5000
CMD flask run --host=0.0.0.0