# Example hello world app deployment that fails
# because of an incorrectly configured readiness probe.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
    env: dev
  name: portfolio
spec:
  replicas: 2
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: python-app
      env: dev
  template:
    metadata:
      labels:
        app: python-app
        env: dev
    spec:
      containers:
      - image: arun161087/flask-portfolio:latest
        name: portfolio
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /index.html
            port: 5000